COPY INTO SHOPSPHERE_DW.STAGING.STG_FACT_SALES_INCREMENTAL
FROM @SHOPSPHERE_DW.STAGING.STG_GOLD_FACT_SALES_INCREMENTAL
FILE_FORMAT = (
    FORMAT_NAME = 'SHOPSPHERE_DW.STAGING.FF_PARQUET'
)
PATTERN = '.*[.]parquet'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

MERGE INTO SHOPSPHERE_DW.ANALYTICS.FACT_SALES AS tgt
USING (
    SELECT *
    FROM SHOPSPHERE_DW.STAGING.STG_FACT_SALES_INCREMENTAL
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY "order_id"
        ORDER BY
            GREATEST(
                COALESCE("updated_at", TO_TIMESTAMP_NTZ('1900-01-01')),
                COALESCE("latest_payment_ts", TO_TIMESTAMP_NTZ('1900-01-01')),
                COALESCE("latest_shipment_ts", TO_TIMESTAMP_NTZ('1900-01-01')),
                COALESCE("_ingested_at", TO_TIMESTAMP_NTZ('1900-01-01'))
            ) DESC,
            "_ingested_at" DESC
    ) = 1
) AS src
ON tgt."order_id" = src."order_id"
WHEN MATCHED THEN UPDATE ALL BY NAME
WHEN NOT MATCHED THEN INSERT ALL BY NAME;
